//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.google.mapsengine.connectors.arcgis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.google.mapsengine.connectors.arcgis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;Google Maps Engine Connectors ToS&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      html, body {
        ///          padding: 0;
        ///          margin: 0;
        ///      }
        ///
        ///      body {
        ///          font-family: arial, sans-serif;
        ///          font-size: 13px;
        ///          line-height: 18px;
        ///      }
        ///
        ///      a {
        ///        color: #1155cc;
        ///        text-decoration: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_dialog_html {
            get {
                return ResourceManager.GetString("about_dialog_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string auth_clearToken_error_unknown {
            get {
                return ResourceManager.GetString("auth_clearToken_error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decode OAuth 2.0 title from accounts.google.com.
        /// </summary>
        internal static string auth_decodeTitleResponse_error_unknown {
            get {
                return ResourceManager.GetString("auth_decodeTitleResponse_error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured while attempting to retrieve your stored OAuth 2.0 state.  Please attempt sign-out and re-authenticate to resolve the issue..
        /// </summary>
        internal static string auth_getToken_error_unknown {
            get {
                return ResourceManager.GetString("auth_getToken_error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string auth_refreshexchange_error_404 {
            get {
                return ResourceManager.GetString("auth_refreshexchange_error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string auth_refreshexchange_error_unknown {
            get {
                return ResourceManager.GetString("auth_refreshexchange_error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have a valid OAuth2 Code.  Authentication settings have been cleared, restart and try again..
        /// </summary>
        internal static string auth_refreshToken_error_tokendoesntexist {
            get {
                return ResourceManager.GetString("auth_refreshToken_error_tokendoesntexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured while attempting to save your OAuth 2.0 state..
        /// </summary>
        internal static string auth_setToken_error_unknown {
            get {
                return ResourceManager.GetString("auth_setToken_error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to exchange the OAuth 2.0 code for a valid access token.  Google Accounts (accounts.google.com) have responded with an error.  Please sign out of the tools and attempt to sign-in again to clear-up the discrepency..
        /// </summary>
        internal static string auth_tokenexchange_error_404 {
            get {
                return ResourceManager.GetString("auth_tokenexchange_error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured while attempting to exchange the OAuth 2.0 code for a valid access token..
        /// </summary>
        internal static string auth_tokenexchange_error_unknown {
            get {
                return ResourceManager.GetString("auth_tokenexchange_error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A temporary copy of the selected dataset was created during the upload process.  Would you like to perminately delete the {0} temporary files in the {1} directory?.
        /// </summary>
        internal static string dialog_dataUpload_tempFileCleanupMessage {
            get {
                return ResourceManager.GetString("dialog_dataUpload_tempFileCleanupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured and the Google Maps Engine map has not be added to your ArcMap..
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_btnAdd_Click_unknownerror {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_btnAdd_Click_unknownerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected to Map.
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_btnAdd_Text {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_btnAdd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_btnCancel_Text {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Search.
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_btnSearch_Text {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_btnSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id.
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_DataGrid_customerId_HeaderText {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_DataGrid_customerId_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google Maps Engine project identifier (cid=)..
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_DataGrid_customerId_ToolTipText {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_DataGrid_customerId_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Description.
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapDescription_HeaderText {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapDescription_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publisher defined description of the map..
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapDescription_ToolTipText {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapDescription_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapId.
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapId_HeaderText {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapId_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project unique map identifier..
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapId_ToolTipText {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapId_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Name.
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapName_HeaderText {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publisher defined name of the map..
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapName_ToolTipText {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_DataGrid_MapName_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching across {numProjects} Google Maps Engine projects.
        /// </summary>
        internal static string dialog_GoogleMapsEngineDirectoryListing_txtSearchSummaryTemplate {
            get {
                return ResourceManager.GetString("dialog_GoogleMapsEngineDirectoryListing_txtSearchSummaryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps Engine for ArcGIS.
        /// </summary>
        internal static string ExtensionTitle {
            get {
                return ResourceManager.GetString("ExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create workspace, the temporary File Geodatabase (FGB) already exists..
        /// </summary>
        internal static string fgdb_GeodatabaseUtilities_createFileGeodatabaseWorkspace_exists {
            get {
                return ResourceManager.GetString("fgdb_GeodatabaseUtilities_createFileGeodatabaseWorkspace_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the referenced File Geodatabase. Does not exist..
        /// </summary>
        internal static string fgdb_GeodatabaseUtilities_deleteFileGeodatabaseWorkspace_notfound {
            get {
                return ResourceManager.GetString("fgdb_GeodatabaseUtilities_deleteFileGeodatabaseWorkspace_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured, unable to delete the local File Geodatabase (FGDB)..
        /// </summary>
        internal static string fgdb_GeodatabaseUtilities_deleteFileGeodatabaseWorkspace_unknown {
            get {
                return ResourceManager.GetString("fgdb_GeodatabaseUtilities_deleteFileGeodatabaseWorkspace_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open referenced File Geodatabase.  Does not exist..
        /// </summary>
        internal static string fgdb_GeodatabaseUtilities_openFileGeodatabaseWorkspace_notfound {
            get {
                return ResourceManager.GetString("fgdb_GeodatabaseUtilities_openFileGeodatabaseWorkspace_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception occured.  Unable to open the referenced File Geodatabase..
        /// </summary>
        internal static string fgdb_GeodatabaseUtilities_openFileGeodatabaseWorkspace_unknown {
            get {
                return ResourceManager.GetString("fgdb_GeodatabaseUtilities_openFileGeodatabaseWorkspace_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open Feature Class..
        /// </summary>
        internal static string GeodatabaseUtilities_createGoogleMapsEngineCatalogFeatureClass_unabletoopen {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_createGoogleMapsEngineCatalogFeatureClass_unabletoopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occured while creating a new Feature Class..
        /// </summary>
        internal static string GeodatabaseUtilities_createGoogleMapsEngineCatalogFeatureClass_unknownexception {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_createGoogleMapsEngineCatalogFeatureClass_unknownexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Description.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_AssetDescription_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_AssetDescription_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceDescription.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_AssetDescription_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_AssetDescription_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Identifier.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_AssetId_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_AssetId_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceId.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_AssetId_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_AssetId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Name.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_AssetName_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_AssetName_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceName.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_AssetName_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_AssetName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_AssetType_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_AssetType_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceType.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_AssetType_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_AssetType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Identifier.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_CustomerId_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_CustomerId_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectId.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_CustomerId_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_CustomerId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_FeatureClassName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_FeatureClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps Engine Asset Catalog.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_LayerName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_LayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_LayerType_Folder {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_LayerType_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Layer.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_LayerType_ImageLayer {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_LayerType_ImageLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector Layer.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_LayerType_VectorLayer {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_LayerType_VectorLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Resource Identifier.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_MapAssetId_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_MapAssetId_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapId.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_MapAssetId_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_MapAssetId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Shared With.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_MapSharedWith_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_MapSharedWith_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapSharedWith.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_MapSharedWith_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_MapSharedWith_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECTID.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_OBJECTID_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_OBJECTID_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECTID.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_OBJECTID_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_OBJECTID_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Resource Identifier.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_ParentAssetId_AliasName {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_ParentAssetId_AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentResourceId.
        /// </summary>
        internal static string GeodatabaseUtilities_schema_ParentAssetId_Name {
            get {
                return ResourceManager.GetString("GeodatabaseUtilities_schema_ParentAssetId_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gme_logo_transparent {
            get {
                object obj = ResourceManager.GetObject("gme_logo_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve a list of maps..
        /// </summary>
        internal static string GoogleMapsEngineAPI_getMaps_unknownexception {
            get {
                return ResourceManager.GetString("GoogleMapsEngineAPI_getMaps_unknownexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve a list of projects..
        /// </summary>
        internal static string GoogleMapsEngineAPI_getProjects_unknownexception {
            get {
                return ResourceManager.GetString("GoogleMapsEngineAPI_getProjects_unknownexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occured. Unable to make web request..
        /// </summary>
        internal static string GoogleMapsEngineAPI_webrequest_unknownexception {
            get {
                return ResourceManager.GetString("GoogleMapsEngineAPI_webrequest_unknownexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;Google Maps Engine Connectors ToS&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      html, body {
        ///          padding: 0;
        ///          margin: 0;
        ///      }
        ///
        ///      body {
        ///          font-family: arial, sans-serif;
        ///          font-size: 13px;
        ///          line-height: 18px;
        ///      }
        ///
        ///      a {
        ///        color: #1155cc;
        ///        text-decoration: n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string upload_dialog_html {
            get {
                return ResourceManager.GetString("upload_dialog_html", resourceCulture);
            }
        }
    }
}
